### PR TITLE
Add viewport meta tag to layout.

### PR DESCRIPTION
**Pull request by mlg-**
What it says on the tin :) Re: https://github.com/LaunchAcademy/make_it_so/issues/10 (which I just opened)

### CODE REVIEW

**Comment by dpickett** [comment]
:heart: this! @mlg- as a fun challenge, can you modify the test so that it asserts that a meta tag exists that has the proper attributes and correlating values? That would be more assertive, as this test validates the the markup is there, but it doesn't assert that it's all in the same tag. 

As a hint, I would probably use nokogiri to parse the page and use a combination of css selectors and attribute getters in my expectations. 

Let me know if this is more to quickly scratch an itch, or if this challenge is something you'd like to pair on :-) 

Also, we should take a look at the HTML5 Bolierplate to see if there's anything else we'd like to include here. https://html5boilerplate.com/ 

Again, if this is just to get a quick fix I can merge this in and we can work on these things later. This is a great addition :+1:

**Comment by dpickett** [comment]
if nokogiri parsing becomes an issue or creates too much complexity due to ERB, asserting against a regular expression would also result in a more confident expectation.

**Comment by mlg-** [comment]
@dpickett Absolutely! I'm more than happy to make the test better using Nokogiri and/or a robust regex, and I am pretty sure I know how to fix it up. I will re-factor and let you know if I get stuck :smile: 

I agree about the HTML5 boilerplate. I'll take a look and see if there are other opportunities!

**Comment by ipatriot** [comment]
Good job MLG!

**Pull request merged**
